//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Class_Sheduling_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Lectures = new HashSet<Lecture>();
        }
    
        public int Course_Id { get; set; }
        public string Course1 { get; set; }
        public Nullable<int> Faculty_Id { get; set; }
        public Nullable<int> Suject_Id { get; set; }
        public Nullable<int> Year_id { get; set; }
        public Nullable<int> semester_id_ { get; set; }
        public Nullable<int> department_id { get; set; }
    
        public virtual Year Year { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecture> Lectures { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Department Department { get; set; }
    }
}
